
apiVersion: v1
kind: Service
metadata:
  name: nodejs-updated
spec:
  type: NodePort
  selector:
    app: nodejs 
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 31110

#apiVersion: v1
#kind: Service
#metadata:
 # name: nodejs
#spec:
 # type: NodePort
 # ports:
 # - name: http
 #   port: 5000
 #   targetPort: 3000
 #   protocol: TCP
#  selector:
#    app: nodejs
